# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G

java_version=25

plugin_version=2.18.0
is_release=false
minecraft_version=26.2
# dependencies
caffeine_version=3.2.3
commons_collections_version=4.5.0
argon_version=2.12
worldguard_compileVersion=7.0.18-SNAPSHOT
vault_version=1.7.1
# runtime dependencies
worldEdit_runVersion=qNuPcliz
worldGuard_runVersion=7.0.18