# Configuration file
# https://github.com/connection-lost/LockettePro/wiki/*-config.yml
# If there are missing entries, you can add them manually.

# will turn itself off after imported the old config once. Will not import language files
import-fromLockettePro: false
language-file-name: 'en'
enable-quick-protect: true
dependency:
  worldguard:
    enabled: true
  coreprotect:
    enabled: true
lock:
  quick-lock:
    type: NOT_SNEAKING_REQUIRED
  blocked:
    interfere: true
    item-transfer:
      in: false
      out: true
    hopper-minecart: REMOVE
  exemptions:
    -
  expire:
    days: 999
cache:
  seconds: 0
cache-time-seconds: 0
lock-default-create-time-unix: -1
username-pattern: "^.?[a-zA-Z0-9_]{3,16}$"


# material name see: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# legacy block name and block id are not supported!
# changing this list will not invalidate any already placed signs, it will just not allow any new locks.
lockables:
  - MINECRAFT:DOORS
  - MINECRAFT:TRAPDOORS
  - MINECRAFT:SHULKER_BOXES
  - MINECRAFT:FENCE_GATES
  - CHEST
  - TRAPPED_CHEST
  - BARREL
  - CHISELED_BOOKSHELF
  - DECORATED_POT
  - LECTERN
  - FURNACE
  - SMOKER
  - BLAST_FURNACE
  - HOPPER
  - DISPENSER
  - DROPPER
  - BREWING_STAND
  - JUKEBOX
  - BEACON
  - CAMPFIRES
  - MINECRAFT:ANVIL
  - DIAMOND_BLOCK
  - NETHERITE_BLOCK
  - CONDUIT