# Configuration file
# https://github.com/GreenSurvivors/Padlock/wiki/config.yml
# If there are missing entries, you can add them manually.

# will turn itself off after imported the old config once. Will not import language files
import-fromLockettePro: false
#The language file that Padlock will read from.
language-file-name: 'en'
dependency:
  # If set to true and worldguard is installed, this will check if the player is allowed to build when quick protecting / breaking locks.
  worldguard:
    enabled: true
lock:
  #| Option                | Description                                                                                                                                             |
  #|-----------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------|
  #| NOT_SNEAKING_REQUIRED | Quick protect if the player right-clicks with a sign in hand and **not** sneaking                                                                       |
  #| SNEAK_NONRELEVANT     | Quick protect if the player right-clicks with a sign, whenever or not they are sneaking or not (this makes it hard to place signs on protected blocks!) |
  #| SNEAK_REQUIRED        | Quick protect if the player right-clicks with a sign in hand and **not** sneaking                                                                       |
  #| OFF                   | Players can't quick protect and always have to manual lock                                                                                              |
  quick-lock:
    type: NOT_SNEAKING_REQUIRED
  blocked:
    # This will block players from placing blocks that may potentially interfere with a locked block.
    interfere: true
    # This will block items from transferring in/out a locked container
    item-transfer:
      in: false
      out: true
    hopper-minecart: REMOVE
  # List of
  #* EXPLOSION // tnt, creeper, endcrystal, every explosion.
  #* GROWTH
  #* PISTON
  #* REDSTONE
  #* VILLAGER
  #* ENDERMAN
  #* ENDER_DRAGON
  #* WITHER
  #* ZOMBIE
  #* SILVERFISH
  exemptions: []
cache:
  seconds: 0
bedrock-prefix: "."


# for material names see: https://jd.papermc.io/paper/1.20/org/bukkit/Material.html
# for tags see: https://jd.papermc.io/paper/1.20/org/bukkit/Tag.html
# legacy block name and block id are not supported!
# changing this list will not invalidate any already placed signs, it will just not allow any new locks.
#
lockables:
  - MINECRAFT:DOORS
  - MINECRAFT:TRAPDOORS
  - MINECRAFT:SHULKER_BOXES
  - MINECRAFT:FENCE_GATES
  - CHEST
  - TRAPPED_CHEST
  - BARREL
  - CHISELED_BOOKSHELF
  - DECORATED_POT
  - LECTERN
  - FURNACE
  - SMOKER
  - BLAST_FURNACE
  - HOPPER
  - DISPENSER
  - DROPPER
  - BREWING_STAND
  - JUKEBOX
  - BEACON
  - CAMPFIRES
  - DECORATED_POT
  - MINECRAFT:ANVIL
  - DIAMOND_BLOCK
  - NETHERITE_BLOCK
  - CONDUIT