# Configuration file
# https://github.com/GreenSurvivors/Padlock/wiki/config.yml
# If there are missing entries, you can add them manually.

# will turn itself off after imported the old config once. Will not import language files
import-fromLockettePro: false
#The language file that Padlock will read from.
language-file-name: 'en'
dependency:
  worldguard:
    # If set to true and worldguard is enabled, this will check if the player is allowed to build when quick protecting / breaking locks.
    enabled: true
    # If set to true and worldguard is enabled, this will give the player access to locked blocks even if they don't have access to the region else wise.
    # Note: This does NOT allow the player to break locks, even if they are owner of it, when they don't have block break access on the region!
    # Note: We have to check every block at least twice to make this happen. If you experience lag, I would recommend to turn caching on.
    overwrite: false
lock:
  #| Option                | Description                                                                                                                                             |
  #|-----------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------|
  #| NOT_SNEAKING_REQUIRED | Quick protect if the player right-clicks with a sign in hand and **not** sneaking                                                                       |
  #| SNEAK_NONRELEVANT     | Quick protect if the player right-clicks with a sign, whenever or not they are sneaking or not (this makes it hard to place signs on protected blocks!) |
  #| SNEAK_REQUIRED        | Quick protect if the player right-clicks with a sign in hand and **not** sneaking                                                                       |
  #| NO_QUICKLOCK          | Players can't quick-protect and always have to manual lock                                                                                              |
  quick-lock:
    type: NOT_SNEAKING_REQUIRED
  blocked:
    # This will block players from placing blocks that may potentially interfere with a locked block.
    interfere: true
    # This will block items from transferring in/out a locked container
    item-transfer:
      in: false
      out: true
      # How long a hopper should wait until trying to move items again. Range 0 - Integer.MAX_VALUE
      # Note: this cooldown will stay even if the lock was removed from the container!
      cooldown-ticks: 1200
    #| Option  | Description                                                                                |
    #|---------|--------------------------------------------------------------------------------------------|
    #| BLOCKED | Minecarts cant move items in / out of a locked container                                   |
    #| ALLOWED | Minecarts can move items according to the item-transfer option                             |
    #| REMOVE  | Minecarts will get removed from the world when trying to interfere with locked containers  |
    # Note: hopper minecarts don't have cooldowns, so if you experience lag you should turn the remove option on
    hopper-minecart: REMOVE
  # List of
  #* EXPLOSION // tnt, creeper, endcrystal, every explosion.
  #* GROWTH
  #* PISTON
  #* REDSTONE
  #* VILLAGER
  #* ENDERMAN
  #* ENDER_DRAGON
  #* WITHER
  #* ZOMBIE
  #* SILVERFISH
  exemptions: []
  # Experimental feature. This feature will cache a block's lock state.
  # It can dramatically increase your server's performance. Recommended interval is 5~10, 0 is off
cache:
  seconds: 0
bedrock-prefix: "."

# for material names see: https://jd.papermc.io/paper/1.20/org/bukkit/Material.html
# for tags see: https://jd.papermc.io/paper/1.20/org/bukkit/Tag.html
# legacy block name and block id are not supported!
# changing this list will not invalidate any already placed signs, it will just not allow any new locks.
#
lockables:
  - MINECRAFT:DOORS
  - MINECRAFT:TRAPDOORS
  - MINECRAFT:SHULKER_BOXES
  - MINECRAFT:FENCE_GATES
  - CHEST
  - TRAPPED_CHEST
  - BARREL
  - CHISELED_BOOKSHELF
  - DECORATED_POT
  - LECTERN
  - FURNACE
  - SMOKER
  - BLAST_FURNACE
  - HOPPER
  - DISPENSER
  - DROPPER
  - BREWING_STAND
  - JUKEBOX
  - BEACON
  - CAMPFIRES
  - DECORATED_POT
  - MINECRAFT:ANVIL
  - DIAMOND_BLOCK
  - NETHERITE_BLOCK
  - CONDUIT