name: Padlock
main: de.greensurvivors.padlock.Padlock
authors: [ connection_lost, GreensurvivorsTeam ]
softdepend: [ WorldGuard, CoreProtect, LockettePro ]
loadbefore: [ SignShop ]
version: ${version}
api-version: "1.20"
description: >
  Padlock is a chest protection plugin for Paper. It is 80% compatible with original Lockette, but delivers a lot of performance enhancements and feature options.
libraries:
  - org.apache.commons:commons-collections4:4.4
  - org.apache.commons:commons-lang3:3.13.0
  - org.springframework.security:spring-security-crypto:6.1.5
  - org.bouncycastle:bcprov-jdk15on:1.70
  - com.github.ben-manes.caffeine:caffeine:3.1.8

commands:
  padlock:
    usage: |
      /lock
    aliases: [ lock, padlock, lockit ]
  password:
    usage: |
      /password
    aliases: [ pw, applypassword ]
#Permissions are handled in Permission Manager
