name: Padlock
main: de.greensurvivors.padlock.Padlock
authors: [ connection_lost, GreensurvivorsTeam ]
softdepend: [ WorldGuard, LockettePro ]
loadbefore: [ SignShop ]
version: "${version}"
api-version: "${minecraft_version}"
description: ${description}
libraries:
  - org.apache.commons:commons-collections4:${commons_collections_version}
  - com.github.ben-manes.caffeine:caffeine:${caffeine_version}
  - de.mkammerer:argon2-jvm:${argon_version}

commands:
  padlock:
    usage: |
      /lock
    aliases: [ lock, padlock, lockit, lockette ] # lockette alias because we are a successor
  password:
    usage: |
      /password
    aliases: [ pw, applypassword, usepassword ]
#Permissions are handled in Permission Manager
