name: Padlock
main: de.greensurvivors.padlock.Padlock
authors: [ connection_lost, GreensurvivorsTeam ]
softdepend: [ WorldGuard, LockettePro ]
loadbefore: [ SignShop ]
version: ${version}
api-version: "${mcVersion}"
description: >
  Padlock is a chest protection plugin for Paper. It is 80% compatible with original Lockette, but delivers a lot of performance enhancements and feature options.
libraries:
  - org.apache.commons:commons-collections4:4.4
  - org.apache.commons:commons-lang3:3.13.0
  - com.github.ben-manes.caffeine:caffeine:3.1.8
  - de.mkammerer:argon2-jvm:2.11

commands:
  padlock:
    usage: |
      /lock
    aliases: [ lock, padlock, lockit, lockette ] # lockette alias because we are a successor
  password:
    usage: |
      /password
    aliases: [ pw, applypassword, usepassword ]
#Permissions are handled in Permission Manager
